<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1" import="com.cs336.*"%>
<!--Import some libraries that have classes that we need -->
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
		<title>Admin Home</title>
	</head>
	<body>
		<jsp:include page="navBarAdmin.jsp"/>	
		<h1> Admin Home </h1>
		<h2> Welcome, <%=session.getAttribute("userID")%>!</h2>
		
		<%  /*The manager should be able to:
			Add, Edit and Delete information for a customer representative
			Obtain a sales report per month (total revenue per month)
			Produce a list of reservations by transit line or by customer name
			Produce the total revenue generated by a particular transit line, or customer
			Determine which customer generated most total revenue
			Produce a list of the 5 most active transit lines (most reservations per month)*/%>
		
		<form method="post" action="viewCustomerRepresentatives.jsp">
			<input type="submit" value="View Customer Representatives">
		</form>
		
		<hr>
		<form method="post" action="viewSalesReport.jsp">
			<input type="submit" value="View Sales Report (per month)">
		</form>
		
		<hr>
		<form method="post" action="viewReservationsPerLine.jsp">
			<select name="transitLine" required>
			<%
			try{
				ApplicationDB db = new ApplicationDB();	
				Connection connection = db.getConnection();
				Statement statement = connection.createStatement();
				String query = "SELECT lineName FROM transitLine";
				ResultSet rs = statement.executeQuery(query);
				while(rs.next()){
					String val = rs.getString(1);
					out.write("<option value=\"" + val + "\">" + val + "</option>");
				}
			}catch(Exception ex){
				
			}
			%>
			</select>
			<input type="submit" value="View Reservations containing Transit Line">
		</form>

		<hr>
		<form method="post" action="viewReservationsPerCustomer.jsp">
			<select name="customer" required>
			<%
			try{
				ApplicationDB db = new ApplicationDB();	
				Connection connection = db.getConnection();
				Statement statement = connection.createStatement();
				String query = "SELECT username FROM passengers";
				ResultSet rs = statement.executeQuery(query);
				while(rs.next()){
					String val = rs.getString(1);
					out.write("<option value=\"" + val + "\">" + val + "</option>");
				}
			}catch(Exception ex){
				
			}
			%>
			</select>
			<input type="submit" value="View Reservations by Customer">
		</form>
		
		<hr>
		<form method="post" action="totalRevenuePerLine.jsp">
			<select name="transitLine" required>
			<%
			try{
				ApplicationDB db = new ApplicationDB();	
				Connection connection = db.getConnection();
				Statement statement = connection.createStatement();
				String query = "SELECT lineName FROM transitLine";
				ResultSet rs = statement.executeQuery(query);
				while(rs.next()){
					String val = rs.getString(1);
					out.write("<option value=\"" + val + "\">" + val + "</option>");
				}
			}catch(Exception ex){
				
			}
			%>
			</select>
			<input type="submit" value="View Revenue (Per line)">
		</form>
		
		<hr>
		<form method="post" action="totalRevenuePerCustomer.jsp">
			<select name="customer" required>
			<%
			try{
				ApplicationDB db = new ApplicationDB();	
				Connection connection = db.getConnection();
				Statement statement = connection.createStatement();
				String query = "SELECT username FROM passengers";
				ResultSet rs = statement.executeQuery(query);
				while(rs.next()){
					String val = rs.getString(1);
					out.write("<option value=\"" + val + "\">" + val + "</option>");
				}
			}catch(Exception ex){
				
			}
			%>
			</select>
			<input type="submit" value="View Revenue (Per customer)">
		</form>
		
		<hr>
		<form method="post" action="viewBestCustomer.jsp">
			<input type="submit" value="View Best Customer (Total revenue)">
		</form>
		
		<hr>
		<form method="post" action="viewActiveLines.jsp">
			<input type="submit" value="View Top 5 Active Transit Lines">
		</form>
	</body>
</html>