<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1" import="com.cs336.*"%>
<!--Import some libraries that have classes that we need -->
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
		<title>Admin Home</title>
	</head>
	<body>
		<jsp:include page="navBarAdmin.jsp"/>	
		Home page for admins
		
		The manager should be able to:
			Add, Edit and Delete information for a customer representative
			Obtain a sales report per month (total revenue per month)
			Produce a list of reservations by transit line or by customer name
			Produce the total revenue generated by a particular transit line, or customer
			Determine which customer generated most total revenue
			Produce a list of the 5 most active transit lines (most reservations per month)
		
		<form action="viewCustomerRepresentatives.jsp">
			<input type="submit" value="View customer representatives">
		</form>
		<br>
		<br>
	</body>
</html>